shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

overrides:
  "@tiptap/core": "^3.14.0"
  "@tiptap/pm": "^3.14.0"
  "undici": ">=6.23.0"
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
  - sharp

