ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

overrides:
  "@tiptap/core": "^3.14.0"
  "@tiptap/pm": "^3.14.0"
